# Generated by Django 4.2.4 on 2023-08-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ispblog', '0002_services_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='c_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('package', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'car_request',
                'db_table': 'c_request',
                'ordering': ('-id',),
            },
        ),
    ]
