# Generated by Django 4.2.4 on 2023-08-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ispblog', '0004_alter_c_request_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='c_request',
            options={'ordering': ('-id',), 'verbose_name_plural': 'connection request'},
        ),
    ]
