# Generated by Django 4.2.4 on 2023-08-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ispblog', '0005_alter_c_request_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='suport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.DateTimeField()),
                ('active_package', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(blank='True', max_length=50, null='True')),
            ],
            options={
                'verbose_name_plural': 'support request',
                'db_table': 'support',
                'ordering': ('-id',),
            },
        ),
    ]
