# Generated by Django 4.2.4 on 2023-08-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ispblog', '0006_suport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suport',
            name='question',
            field=models.CharField(max_length=50),
        ),
    ]
