# Generated by Django 4.2.4 on 2023-08-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ispblog', '0007_alter_suport_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suport',
            name='active_package',
            field=models.CharField(blank='True', max_length=50, null='True'),
        ),
    ]
