# Generated by Django 4.2.4 on 2023-08-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ispblog', '0008_alter_suport_active_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suport',
            name='phone',
            field=models.CharField(blank='True', max_length=50, null='True'),
        ),
        migrations.AlterField(
            model_name='suport',
            name='question',
            field=models.CharField(blank='True', max_length=50, null='True'),
        ),
    ]
